### ISSUE TITLE
bridge is not sending all messages matrix>slack

### ISSUE THREAD

**Issue by ericmigi** [Sorunome/mx-puppet-slack#62] opened 2020-05-07 06:43 UTC
weird: bridge is working correctly in some rooms, but only working in slack>matrix direction in others. matrix>slack messages do not appear bridged in slack. 

Here is a message I sent from matrix>slack that does not work
```
May-7 06:41:12.067 [MatrixEventHandler] info: Got new message in !iXEfLHSKkzRBcaPYOi:nova.chat from @eric:nova.chat!
May-7 06:41:12.068 [MatrixEventHandler] info: Handling text event with msgtype m.text...
127.0.0.1 - - [07/May/2020:06:41:12 +0000] "PUT /_matrix/app/v1/transactions/63670?access_token=Hlct33h1cFfSj8YQ9giYMLbFywwaJGWXdI1rZhg49kdFLWRFrGSPRaSJ13el3WcO HTTP/1.1" 200 2 "-" "Python/3.8 aiohttp/3.6.2"
May-7 06:41:12.080 [bot-sdk-MatrixLiteClient] info: (REQ-28) GET https://asmux.nova.chat/_matrix/client/r0/rooms/!iXEfLHSKkzRBcaPYOi%3Anova.chat/event/%24sLR1j5Z6UjFB0OAETqeX5nix0jUHIU2VHU8P1RbKew0
May-7 06:41:12.440 [bot-sdk-MatrixLiteClient] info: (REQ-29) GET https://asmux.nova.chat/_matrix/client/r0/rooms/!iXEfLHSKkzRBcaPYOi%3Anova.chat/state/m.room.member/%40_eric_slack___t02_a11_s1_m%3D2d_u_v3_n5_u880%3Anova.chat
May-7 06:41:12.707 [SlackPuppet:slack] info: Received create request for user update puppetId=1 userId=T02A11S1M-UV3N5U880
May-7 06:41:12.708 [SlackPuppet:slack] info: Received create request for user update puppetId=2 userId=T02A11S1M-UV3N5U880
May-7 06:41:12.709 [SlackPuppet:slack] info: Received create request for user update puppetId=3 userId=T02A11S1M-UV3N5U880
(node:1) UnhandledPromiseRejectionWarning: Error: An API error occurred: method_not_supported_for_channel_type
    at Object.platformErrorFromResult (/opt/mx-puppet-slack/node_modules/@slack/web-api/dist/errors.js:50:33)
    at WebClient.apiCall (/opt/mx-puppet-slack/node_modules/@slack/web-api/dist/WebClient.js:485:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
```

silly logs
```
May-7 06:41:12.067 [MatrixEventHandler] info: Got new message in !iXEfLHSKkzRBcaPYOi:nova.chat from @eric:nova.chat!
May-7 06:41:12.068 [MatrixEventHandler] info: Handling text event with msgtype m.text...
May-7 06:41:12.068 [Postgres] silly: All: SELECT * FROM event_store WHERE puppet_id = $p AND room_id = $room AND matrix_id = $m
May-7 06:41:12.080 [bot-sdk-MatrixLiteClient] info: (REQ-28) GET https://asmux.nova.chat/_matrix/client/r0/rooms/!iXEfLHSKkzRBcaPYOi%3Anova.chat/event/%24sLR1j5Z6UU8P1RbKew0
May-7 06:41:12.438 [bot-sdk-MatrixLiteClient] debug: (REQ-28 RESP-H200) {
  type: 'm.room.message',
  room_id: '!iXEfLHSKkzRBcaPYOi:nova.chat',
  sender: '@_eric_slack___t02_a11_s1_m=2d_u_v3_n5_u880:nova.chat',
  content: {
    msgtype: 'm.text',
    body: '> <@eric:nova.chat> Puzzle is done! Who wants it next?\n' +
      '\n' +
      'Really tempted but probably shouldn’t. It’ll take over all my attention until I’m done with it.',
    format: 'org.matrix.custom.html',
    formatted_body: '<mx-reply><blockquote>\n' +
      '\t<a href="https://matrix.to/#/!iXEfLHSKkzRBcaPYOi:nova.chat/$szozCTpEhtdaehDx0x6afSIggcg1O4KxOVOzVQJ9u5s">In reply to</a>\n' +
      '\t<a href="https://matrix.to/#/@eric:nova.chat">@eric:nova.chat</a>\n' +
      '\t<br><p>Puzzle is done! Who wants it next?</p>\n' +
      '</blockquote></mx-reply><p>Really tempted but probably shouldn’t. It’ll take over all my attention until I’m done with it.</p>',
    source: 'slack',
    'm.relates_to': { 'm.in_reply_to': [Object] },
    external_url: ''
  },
  origin_server_ts: 1588832754937,
  unsigned: { age: 917456 },
  event_id: '$sLR1j5Z6UjFIU2VHU8P1RbKew0',
  user_id: '@_eric_slack___t02_a11_s1_m=2d_u_v3_n5_u880:nova.chat',
  age: 917456
}
May-7 06:41:12.439 [bot-sdk-Metrics] debug: matrix_client_function_call
May-7 06:41:12.439 [bot-sdk-Metrics] debug: matrix_client_function_call
May-7 06:41:12.440 [bot-sdk-MatrixLiteClient] info: (REQ-29) GET https://asmux.nova.chat/_matrix/client/r0/rooms/!%3Anova.chat/state/m.room.member/%40_eric_slack___t02_a11_s1_m%3D2d_u_v3_n5_u880%3Anova.chat
May-7 06:41:12.705 [bot-sdk-MatrixLiteClient] debug: (REQ-29 RESP-H200) {
  membership: 'join',
  displayname: 'catheryn  - YC Slack',
  avatar_url: 'mxc://nova.chat/THswcDLKUemoPMxGrmgdpKLp'
}
May-7 06:41:12.705 [bot-sdk-Metrics] debug: matrix_client_function_call
May-7 06:41:12.707 [bot-sdk-Metrics] debug: matrix_client_function_call
May-7 06:41:12.707 [SlackPuppet:slack] info: Received create request for user update puppetId=1 userId=T02A11S1M-
```

**Comment by twouters** [comment] 2020-05-07 09:07
Dupe of #59 :)

**Comment by twouters** [comment] 2020-05-07 09:09
Feel free to give https://github.com/Sorunome/soru-slack-client/pull/5 a try

**Comment by Sorunome** [comment] 2020-05-07 11:45
fixed in https://github.com/Sorunome/soru-slack-client/commit/cf594f17acfd256ea7b8d8dad0cd666b201177d7

**Closed by Sorunome** 2020-05-07 11:45 UTC
