### ISSUE TITLE
Unable to send links Matrix -> Slack

### ISSUE THREAD

**Issue by matejdro** [Sorunome/mx-puppet-slack#49] opened 2020-04-07 14:28 UTC
Weird thing just started happening today. Every time I want to send a http link to Slack contact via Matrix, I will get this error and message will not be delivered:

```
Apr-7 14:16:55.143 [MatrixEventHandler] [32minfo[39m: Got new message in !MY_ID from @matejdro:MY_SERVER!
Apr-7 14:16:55.143 [MatrixEventHandler] [32minfo[39m: Handling text event with msgtype m.text...
Apr-7 14:16:55.143 [MatrixEventHandler] [34mdebug[39m: Emitting message event...
[ERROR]  WebClient:6 must be more than 0 characters [json-pointer:/blocks/0/elements/0/elements/0/text]
(node:1) UnhandledPromiseRejectionWarning: Error: An API error occurred: invalid_blocks
    at Object.platformErrorFromResult (/opt/mx-puppet-slack/node_modules/@slack/web-api/dist/errors.js:50:33)
    at WebClient.apiCall (/opt/mx-puppet-slack/node_modules/@slack/web-api/dist/WebClient.js:485:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 43)
```

Interestingly enough, if I prefix the message with space (so I type in single space first and then paste the link), it goes through. 

This is with version https://github.com/Sorunome/mx-puppet-slack/commit/200bc62d10aa7a05db2bb7e3f0ebd0dd3fb3afa3

**Comment by Sorunome** [comment] 2020-04-07 14:29
Duplicate of https://github.com/Sorunome/matrix-slack-parser/issues/4

**Closed** 2020-04-07 14:31 UTC
