### ISSUE TITLE
one-on-one chats don't have the slack name eg - YC after the persons name

### ISSUE THREAD

**Issue by ericmigi** [Sorunome/mx-puppet-slack#9] opened 2019-07-04 00:24 UTC
![image](https://user-images.githubusercontent.com/1048265/60631976-63c5e380-9db7-11e9-8487-9a3f096b91f8.png)

**Comment by ericmigi** [comment] 2019-07-04 00:24
should be kat - YC

**Comment by Sorunome** [comment] 2019-07-04 08:22
that is actually also currently intended behaviour: the bridge sets neither an avatar nor a name, thus the client displays the avatar and name of the other participant

**Comment by ericmigi** [comment] 2019-07-04 18:23
for now, I think it would be best to have the bridge name the portal "username - slackname Slack" so from a filtering perspective it's easy to ctl-k search for the user and differentiate from other portals you might have with other people

**Comment by Sorunome** [comment] 2020-01-28 16:30
This is fixed with the name patterns

**Closed by Sorunome** 2020-01-28 16:30 UTC
